// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: mobileingest/v1/api.proto
//
package mobileingest.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

public interface MobileIngestServiceClientInterface {
  public suspend fun activity(request: Api.Request, headers: Headers = emptyMap()):
      ResponseMessage<Api.Response>
}
