// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: mobileingest/v1/api.proto
//
package mobileingest.v1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

public class MobileIngestServiceClient(
  private val client: ProtocolClientInterface,
) : MobileIngestServiceClientInterface {
  override suspend fun activity(request: Api.Request, headers: Headers):
      ResponseMessage<Api.Response> = client.unary(
    request,
    headers,
    MethodSpec(
    "mobileingest.v1.MobileIngestService/Activity",
      mobileingest.v1.Api.Request::class,
      mobileingest.v1.Api.Response::class,
      StreamType.UNARY,
    ),
  )

}
