# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'
use_frameworks!

install! 'cocoapods', :integrate_targets => false

target 'Sample' do
  pod 'FirebaseCore'
  pod 'FirebaseCoreInternal'
  pod 'FirebaseMessaging'
  pod 'FirebaseInstallations'
  pod 'FirebaseAnalytics'

end
