name: DitoSDK
options:
  bundleIdPrefix: br.com.dito
  deploymentTarget:
    iOS: 16.0
targets:
  Sample:
    type: application
    platform: iOS
    sources:
      - path: SampleApplication
    dependencies:
      - target: DitoSDK
    configFiles:
      Debug: Pods/Target Support Files/Pods-Sample/Pods-Sample.debug.xcconfig
      Release: Pods/Target Support Files/Pods-Sample/Pods-Sample.release.xcconfig
    preBuildScripts:
      - script: "${PODS_ROOT}/Target Support Files/Pods-Sample/Pods-Sample-frameworks.sh"
        name: "[CP] Embed Pods Frameworks"
        runOnlyWhenInstalling: false
        showEnvVars: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.dito.samplesdk
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIBackgroundModes: remote-notification

  DitoSDK:
    type: framework
    platform: iOS
    sources:
      - path: DitoSDK/Sources
        name: Sources
        createIntermediateGroups: true
      - path: DitoSDK/Persistence
        name: Persistence
        createIntermediateGroups: true
      - path: DitoSDK/DitoSDK/DitoSDK.docc
        name: Documentation
        optional: true
    settings:
      base:
        INFOPLIST_FILE: DitoSDK/Info.plist

  DitoSDKTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DitoSDKTests
    dependencies:
      - target: DitoSDK
    settings:
      base:
        INFOPLIST_FILE: DitoSDKTests/Info.plist

