name: DitoSDK
options:
  bundleIdPrefix: br.com.dito
  deploymentTarget:
    iOS: 16.0
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 12.10.0
  Promises:
    url: https://github.com/google/promises.git
    from: 2.4.0
targets:
  Sample:
    type: application
    platform: iOS
    sources:
      - path: SampleApplication
        excludes:
          - "*.md"
          - "ViewControllerComplete.swift"
          - "Main.storyboard"
          - "NotificationDebugViewController.swift"
          - "EnvLoader.swift"
    dependencies:
      - target: DitoSDK
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseMessaging
      - package: Promises
        product: FBLPromises
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.dito.example.samplesdk
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIBackgroundModes: remote-notification

  DitoSDK:
    type: framework
    platform: iOS
    sources:
      - path: DitoSDK/Sources
        name: Sources
        createIntermediateGroups: true
      - path: DitoSDK/Persistence
        name: Persistence
        createIntermediateGroups: true
      - path: DitoSDK/DitoSDK/DitoSDK.docc
        name: Documentation
        optional: true
    settings:
      base:
        INFOPLIST_FILE: DitoSDK/Info.plist

  DitoSDKTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DitoSDKTests
    dependencies:
      - target: DitoSDK
    settings:
      base:
        INFOPLIST_FILE: DitoSDKTests/Info.plist

